### ISSUE TITLE
Code switching inputs

### ISSUE THREAD

**Issue by jayakrishnanmm** [saharmor/whisper-playground#19]
import whisper
model = whisper.load_model("large-v2")
result = model.transcribe('test_file/EN-ZH.wav')
print(result['text'])
The above audio contains a mix  of English and Chinese language. But the result  is just  pure English  only. How  did  you  get  code-switch output ? The same   file played   back  in the [demo](https://whisperui.monsterapi.ai/)  gives the  expected  output. Pls tell  me  how it is done

**Comment by saharmor** [comment]
Are you sure you're not using the English only Whisper models? https://github.com/openai/whisper#available-models-and-languages

**Comment by shanky100** [comment]
> import whisper model = whisper.load_model("large-v2") result = model.transcribe('test_file/EN-ZH.wav') print(result['text']) The above audio contains a mix of English and Chinese language. But the result is just pure English only. How did you get code-switch output ? The same file played back in the [demo](https://whisperui.monsterapi.ai/) gives the expected output. Pls tell me how it is done

I guess that large models of whisper are only with English supports.  You can try medium model of whisper.
