### ISSUE TITLE
Pyaudio 

### ISSUE THREAD

**Issue by Alastair1234** [saharmor/whisper-playground#2]
Looks like a great project!  
During the Install the backend and frontend environmet sh install_playground.sh I'm getting an error:

<img width="564" alt="image" src="https://user-images.githubusercontent.com/24195319/196029403-10446519-26d1-4c78-986d-d5cc7056f754.png">

**Comment by saharmor** [comment]
Can you try following the suggestions in this thread and report back? https://stackoverflow.com/questions/73268630/error-could-not-build-wheels-for-pyaudio-which-is-required-to-install-pyprojec

**Comment by chrismbirmingham** [comment]
> 

I also had the same issue, on ubuntu I just used `sudo apt-get install portaudio19-dev`

**Comment by saharmor** [comment]
Thanks for the flag. @HarHarLinks what command did you run to install portaudio? I'll add it to the README

**Comment by HarHarLinks** [comment]
command is `sudo pacman -S portaudio` on arch linux.

**Comment by saharmor** [comment]
Perfect, I've updated the readme, thanks.
