### ISSUE TITLE
How to add a new language in the interface?

### ISSUE THREAD

**Issue by nothingcomeseasy** [saharmor/whisper-playground#3]
Hello! Thanks for the whisper-playground! I'm having lots of fun :)

I'd like to add portuguese in the playground, is it possible?

**Comment by saharmor** [comment]
Sure, just added Portuguese and all the other languages 98 language Whisper supports 
<img width="799" alt="image" src="https://user-images.githubusercontent.com/6180201/196081127-2bc82717-51ec-4cb0-b1c0-b53168273ed5.png">
