### ISSUE TITLE
Purple dots keep going & no transcription.

### ISSUE THREAD

**Issue by BrianFenn** [saharmor/whisper-playground#6]
<img width="550" alt="Screenshot 2022-10-21 115252" src="https://user-images.githubusercontent.com/34203314/197268978-2db30773-7160-46c6-9e3c-11aad0d7dd58.png">

Purple dots keep going, but no transcription is done.  Any ideas why?  I followed everything in the readme file.  
OS: Windows 11
Python: 3.9.7

**Comment by saharmor** [comment]
@BrianFenn can you please attach a screenshot of your [console output](https://balsamiq.com/support/faqs/browserconsole/#:~:text=To%20open%20the%20developer%20console,(on%20Windows%2FLinux).)?

**Comment by BrianFenn** [comment]
<img width="954" alt="image" src="https://user-images.githubusercontent.com/34203314/197376981-e773e748-312e-4bd4-848a-db6fdf32e39a.png">

**Comment by BrianFenn** [comment]
One guy had a similar problem and says that his react app was "still sending a request to 127.0.0.1 despite having changed the IP address to [1921.168.00.5] on his code."  

So he said the problem was that the request from the app wasn't being sent sent to the correct IP (because the code was never updated when rebuilding).  

Do you think that is what I am experiencing?

[https://stackoverflow.com/questions/69508554/cross-origin-request-blocked-the-same-origin-policy-disallows-reading-the-remot]

**Comment by wpuricz** [comment]
I did have a CORS issue. Solved it by:
1. Adding this in the package.json "proxy":"http://127.0.0.1:8000",
2. Changing the axios.post in App.js to http://127.0.0.1:8000/transcribe

**Comment by yubrshen** [comment]
For my environment with Ubuntu/WSL2 in Windows 11, with the changes:

1. Adding this in the package.json "proxy":"http://127.0.0.1:8000/",
2. Changing the axios.post in App.js to http://127.0.0.1:8000/transcribe

It worked.

**Comment by shanky100** [comment]
Hi @yubrshen where I can find this axios.post in App.js, can you please share the changed code if possible.
